// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogScaffold: typeof import('./src/blog/components/BlogScaffold.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLink: typeof import('~icons/carbon/link')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    DropdownItem: typeof import('./src/blog/components/DropdownItem.vue')['default']
    Footer: typeof import('./src/common/components/Footer.vue')['default']
    MdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    MdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
    MdiFacebook: typeof import('~icons/mdi/facebook')['default']
    MdiTwitter: typeof import('~icons/mdi/twitter')['default']
    Navbar: typeof import('./src/common/components/Navbar.vue')['default']
    README: typeof import('./src/common/components/README.md')['default']
    VButton: typeof import('./src/common/components/VButton.vue')['default']
  }
}

export { }
